ALTER TABLE smf_members ADD `ow_id` MEDIUMINT(11) DEFAULT NULL;
ALTER TABLE smf_boards ADD `ow_id` MEDIUMINT(11) DEFAULT NULL;
ALTER TABLE smf_categories ADD `ow_id` MEDIUMINT(11) DEFAULT NULL;
ALTER TABLE smf_topics ADD `ow_id` MEDIUMINT(11) DEFAULT NULL;
ALTER TABLE smf_messages ADD `ow_id` MEDIUMINT(11) DEFAULT NULL;